### ISSUE TITLE
[bug] qrcode doesn't appear, shows infinite loader when @walletconnect/sign-client > 2.10.0

### ISSUE THREAD

**Issue by jakim929** [worldcoin/idkit-js#153]
I think something breaks when initializing the walletconnect client in idkit in @walletconnect/sign-client > 2.10.0.

https://github.com/worldcoin/world-id-cloud-template - this repo doesn't run into the same issue because the pnpm-lock already locked the @walletconnect/sign-client dependency to 2.9.1. 

### Works: Pin @walletconnect/sign-client dependency to 2.9.0
https://stackblitz.com/edit/stackblitz-starters-xv5egu?file=app%2Fpage.tsx

### Doesn't work: Don't do anything, just install idkit-js
https://stackblitz.com/edit/stackblitz-starters-nphvy5?file=app%2Fpage.tsx

**Comment by 0xPenryn** [comment]
This issue appears to only be present on versions 2.10.0 and 2.10.1 of @walletconnect/sign-client, I was able to reproduce. Using version 2.10.2 (latest) resolves the issue. Can you confirm that this resolves the issue?

**Comment by 0xPenryn** [comment]
Closing, as this issue is resolved.
