### ISSUE TITLE
[ERROR] Could not resolve "@worldcoin/idkit"

### ISSUE THREAD

**Issue by hsapphire** [worldcoin/idkit-js#222]
worldcoin/idkit-core:dev: CLI Watching for changes in "."
@worldcoin/idkit-core:dev: CLI Ignoring changes in "**/{.git,node_modules}/**" | "build"
@worldcoin/idkit-standalone:dev: X [ERROR] Could not resolve "@worldcoin/idkit"
@worldcoin/idkit-standalone:dev: 
@worldcoin/idkit-standalone:dev:     src/index.tsx:2:41:
@worldcoin/idkit-standalone:dev:       2 │ import { IDKitWidget, type Config } from '@worldcoin/idkit'
@worldcoin/idkit-standalone:dev:         ╵                                          ~~~~~~~~~~~~~~~~~~
@worldcoin/idkit-standalone:dev: 
@worldcoin/idkit-standalone:dev:   The module "./build/index.js" was not found on the file system:
@worldcoin/idkit-standalone:dev: 
@worldcoin/idkit-standalone:dev:     node_modules/@worldcoin/idkit/package.json:16:13:
@worldcoin/idkit-standalone:dev:       16 │       "import": "./build/index.js",
@worldcoin/idkit-standalone:dev:          ╵                 ~~~~~~~~~~~~~~~~~~
@worldcoin/idkit-standalone:dev: 
@worldcoin/idkit-standalone:dev:   You can mark the path "@worldcoin/idkit" as external to exclude it from the bundle, which will remove this error.
@worldcoin/idkit-standalone:dev: 
@worldcoin/idkit-standalone:dev: X [ERROR] Could not resolve "@worldcoin/idkit/internal"
@worldcoin/idkit-standalone:dev: 
@worldcoin/idkit-standalone:dev:     src/index.tsx:3:48:
@worldcoin/idkit-standalone:dev:       3 │ ... __, useIDKitStore, ConfigSource } from '@worldcoin/idkit/internal'
@worldcoin/idkit-standalone:dev:         ╵                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~
@worldcoin/idkit-standalone:dev: 
@worldcoin/idkit-standalone:dev:   The module "./build/internal.js" was not found on the file system:

**Comment by Yokymia32** [comment]
🩷
