### ISSUE TITLE
Adding `IDKit.isInitialized` Flag to Check Initialization Status

### ISSUE THREAD

**Issue by erados** [worldcoin/idkit-js#256]
**Description:**

Currently, the IDKit can only be initialized once. To ensure that the initialization process is managed correctly, it would be beneficial to have a flag indicating whether the IDKit has been initialized. This flag, `IDKit.isInitialized`, would help developers avoid reinitialization attempts and manage the initialization state more effectively.

**Proposed Solution:**

Introduce a boolean flag `IDKit.isInitialized` that:

- Defaults to `false` before initialization.
- Changes to `true` once the IDKit has been successfully initialized.

**Benefits:**

1. **Prevent Reinitialization:** By checking the `isInitialized` flag, developers can avoid unnecessary or erroneous reinitialization attempts.
2. **State Management:** Provides a clear and straightforward way to manage the initialization state within the application.
3. **Error Handling:** Helps in implementing more robust error handling by checking the initialization state before performing operations that depend on IDKit.

**Example Usage:**

```javascript
if (!IDKit.isInitialized) {
    IDKit.initialize();
}

// Safe to proceed with operations that require IDKit to be initialized
if (IDKit.isInitialized) {
    // Perform operations
}
```

Thank you for considering this enhancement. It would greatly improve the usability and reliability of the IDKit in various scenarios.

![image](https://github.com/worldcoin/idkit-js/assets/19205043/440f2411-2e48-45f4-a169-51d733f5ae37)

**Comment by Ivanciro27** [comment]
if (!IDKit.isInitialized) {
    IDKit.initialize();
}

// Safe to proceed with operations that require IDKit to be initialized
if (IDKit.isInitialized) {
    // Perform operations
}
