### ISSUE TITLE
Feature Request: Implement IDKit.close() API for  close modal on standalone

### ISSUE THREAD

**Issue by wenweih** [worldcoin/idkit-js#257]
May I know do it any plan to add close modal API, something like that: `IDKit.close()`

I am currently utilizing IDKit in my project and have encountered situations where I need to programmatically close the modal generated by IDKit. 

This functionality is particularly necessary in the context of handling verification callbacks, where an automatic or manual dismissal of the modal may be required based on the verification outcome or other logic within the handleVerify callback function.

Thanks.

**Comment by andy-t-wang** [comment]
Hi we can look into this

**Comment by andy-t-wang** [comment]
Are you using react or standalone

**Comment by andy-t-wang** [comment]
If you're using react we do have hooks you can use to close the modal

https://docs.worldcoin.org/reference/idkit
